spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/athletiq
    driver-class-name: org.postgresql.Driver
    username: athletiq_user
    password: athletiq_password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_SERVICE_USERNAME}
    password: ${EMAIL_SERVICE_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
app:
  web:
    reset-url: http://localhost:8100/reset-password
    mobile:
      reset-scheme: athletiq


# Server Port
server:
  port: 6969