spring:
  datasource:
    url: jdbc:postgresql://${{Postgres.PGHOST}}:5432/${{Postgres.PGDATABASE}}
    username: ${{Postgres.PGUSER}}
    password: ${{Postgres.PGPASSWORD}}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_SERVICE_USERNAME}
    password: ${EMAIL_SERVICE_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true