spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

  application:
    name: athletiq
rsa:
  private-key: "classpath:/certs/private.pem"
  public-key: "classpath:/certs/public.pem"

server:
  port: 8080