spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

  application:
    name: athletiq

rsa:
  private-key: ${RSA_PRIVATE_KEY:classpath:/certs/private.pem}
  public-key: ${RSA_PUBLIC_KEY:classpath:/certs/private.pem}

server:
  port: 8080